[[redirects]]
  from = "https://meek-kangaroo-892565.netlify.app/*"
  to = "https://magmatranslation.com/stats/:splat"
  status = 301
  force = true



[[redirects]]
  from = "/*"
  to = "/pages/:splat/"
  status = 200
