[[redirects]]
  from = "https://meek-kangaroo-892565.netlify.app/*"
  to = "https://magmatranslation.com/stats/:splat"
  status = 301
  force = true




  [[redirects]]
  from = "https://stats.magmatranslation.com/*"
  to = "https://magmatranslation.com/stats/:splat"
  status = 301
  force = true